### ISSUE TITLE
Define a standard release cycle

### ISSUE THREAD

**Issue by matt-mazzucato** [astarte-platform/astarte#735]
Astarte releases must be made public at a predetermined and fixed pace: two stable releases per year must be published, namely during the months of June and December. 

Astarte releases should be kept synchronized to some extent with the Astarte Operator releases (see https://github.com/astarte-platform/astarte-kubernetes-operator/issues/306). In particular, the following statements are true:
- any changes that impact the Astarte CRDs must be implemented and tested at least 15 days before the Operator's release (any further changes impacting CRDs are moved to the next release cycle) 
- an `alpha` version must be released 15 days before an Operator's release
- a stable release should be made public one month after an Operator's release

**Comment by bettio** [comment]
Since v1.1 and Astarte Kubernetes Operator v22.11 a release cycle is in place:
- Astarte and the Kubernetes Operator will be released twice a year
- Astarte and the Kubernetes Operator versioning will be decoupled
- Astarte  Kubernetes Operator will follow calendar versioning, while Astarte will continue with semver
